### ISSUE TITLE
Is it okay to use arduino mega 2560?

### ISSUE THREAD

**Issue by seo2730** [PINTO0309/zumo32u4#1]
I will use rplidar A1, arduino mega 2560 and raspiberry 3B. Is it okay to use your code???

**Comment by PINTO0309** [comment]
I do not own "arduino mega 2560", so I can not answer accurate things.
However, I think that there is no difference other than arduino's buffer size.
Please adjust the size according to your environment "11. Remodel the rosserial library. Execute below." procedure.

**Comment by seo2730** [comment]
Is this code to adjust the buffer size???

typedef NodeHandle_<ArduinoHardware, 15, 15, 128, 1024, FlashReadOutBuffer_> NodeHandle;

If it’s right, what does this code mean? Can you explain?

**Comment by PINTO0309** [comment]
>Is this code to adjust the buffer size???

Yes. That's right.

>If it’s right, what does this code mean? Can you explain?

"publish buffer" = 1024 Bytes
"subscribe buffer" = 128 Bytes

The total size should not exceed your arduino buffer size.
example1: 25 x 512 + 25 + 512 = 25600 Bytes
example2: 15 x 128 +15 x1024 = 17280 Bytes

If your arduino buffer size is small, please reduce the size of the message you are publishing.
Also, the total number of bytes in the following string × 10 must not exceed the size of the publish buffer.

- zumo32u4arduino.ino
```cpp
  String s = "";
  s += timer;          // [0]  Elapsed time since program started (milli second)
  s += ',';
  s += compass.a.x;    // [1]  Accelerometer.x
  s += ',';
  s += compass.a.y;    // [2]  Accelerometer.y
  s += ',';
  s += compass.a.z;    // [3]  Accelerometer.z
  s += ',';
  s += compass.m.x;    // [4]  Magnetometer.x
  s += ',';
  s += compass.m.y;    // [5]  Magnetometer.y
  s += ',';
  s += compass.m.z;    // [6]  Magnetometer.z
  s += ',';
  s += vleft;          // [7]  Left Morter velocity (speed of motor)
  s += ',';
  s += vright;         // [8]  Right Morter velocity (speed of motor)
  s += ',';
  s += positionLeft;   // [9]  Left Morter odometry (Rotation angle of motor)
  s += ',';
  s += positionRight;  // [10] Right Morter odometry (Rotation angle of motor)
  s += ',';
  s += gyro.g.x;       // [11] Gyrometer.x
  s += ',';
  s += gyro.g.y;       // [12] Gyrometer.y
  s += ',';
  s += gyro.g.z;       // [13] Gyrometer.z
  
  //Serial.println(s);  // Debug Print

  str_msg.data = s.c_str();
  chatter.publish(&str_msg);
```

See.
**ROS Answers**
**https://answers.ros.org/question/73627/how-to-increase-rosserial-buffer-size/**

**My Japanese article**
**https://qiita.com/PINTO/items/9aa737c284dc4e8212f1#-raspberrypi-%E3%81%A8-arduino-%E3%81%B8%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E5%AE%9F%E8%A3%85**

**Comment by seo2730** [comment]
Thanks~ I will try it.
